# Generated by Django 6.1 on 2026-08-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyectos', '0002_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En_progreso'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=11),
        ),
    ]
