# Generated by Django 6.1 on 2026-08-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyectos', '0003_alter_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(default='img/logo.png', upload_to='img/'),
        ),
    ]
